<?php
/** Static/adversarial regression for the tenth fresh File 20 ten-round review. */
declare(strict_types=1);
$root=dirname(__DIR__);$read=static function($path)use($root){return(string)file_get_contents($root.'/'.$path);};
$main=$read('sabri-unified-application-shell.php');$plugin=$read('includes/class-plugin.php');$defaults=$read('includes/class-defaults.php');$tenth=$read('includes/class-future-shell-v5-tenth-hardening.php');$slots=$read('includes/class-native-content-slots.php');$safe=$read('includes/class-safe-mode.php');$health=$read('includes/class-plan-v4-contract-health.php');$fail=[];
$assert=static function($ok,$label)use(&$fail):void{if(!$ok)$fail[]=$label;};
$assert(strpos($main,'* Version: 1.4.16')!==false&&strpos($main,"SABRI_SHELL_VERSION', '1.4.16")!==false,'current release 1.4.16 preserves tenth hardening');
$assert(strpos($main,'FutureShellV5TenthHardening::register();')!==false,'tenth hardening registered');$assert(strpos($tenth,"CONTRACT_VERSION = '1.0.10'")!==false,'tenth contract 1.0.10');
$assert(strpos($plugin,'HomeFeed::register();')===false,'File20 local HomeFeed runtime not registered');$assert(strpos($tenth,"'sabri_shell_home_feed' !== sanitize_key")!==false,'retired File20 feed shortcode removed');$assert(strpos($tenth,"'auto_insert' => false")!==false&&strpos($tenth,"'posts_count' => 0")!==false,'retired feed inert');$assert(strpos($tenth,"\$value['navigation']['home']['shortcode'] = 'sabri_complete_home_feed';")!==false,'legacy feed shortcode migration');$assert(strpos($defaults,"'home_feed'")!==false,'legacy defaults migration-readable');
foreach(['sabri_shell_home_before_main','sabri_shell_home_main','sabri_shell_home_after_main','sabri_shell_home_right_sidebar','sabri_shell_news_main']as$hook)$assert(strpos($slots,$hook)!==false,'native slot '.$hook);
$assert(strpos($slots,"'' !== trim( \$main ) ? \$main : \$content")!==false,'native output replaces legacy content');$assert(strpos($slots,'self::$home_content_dispatched')!==false&&strpos($slots,'self::$news_content_dispatched')!==false,'native slots one-per-request');$assert(strpos($slots,'catch ( \\Throwable $error )')!==false,'slot provider failure isolated');
$assert(strpos($tenth,"remove_filter( 'body_class', array( Renderer::class, 'body_classes' )")!==false,'legacy visual body classes retired');$assert(strpos(substr($tenth,strpos($tenth,'structural_body_classes'),1800),"['appearance']")===false,'structural classes no appearance state');
$assert(strpos($tenth,'membership-core-1.2.18-reviewed-head')!==false&&strpos($tenth,"'critical' => 13")!==false&&strpos($tenth,"'high' => 44")!==false,'File00 audit truth');$assert(strpos($tenth,"'production_safe_implied' => false")!==false&&strpos($tenth,"'known_external_release_blockers' => true")!==false,'File00 not production-safe implied');
$assert(strpos($tenth,'file26_search_surface_only')!==false&&strpos($tenth,"'file20_fallback' => false")!==false,'File26-only search');$assert(strpos($health,"'status' => 'unavailable'")!==false&&strpos($health,"'file20_fallback' => false")!==false,'base search fail-closed');
$assert(strpos($tenth,'bind_actual_provider_versions')!==false,'provider versions bound');$assert(strpos($tenth,"preg_match( '/^\\d+\\.\\d+\\.\\d+$/', \$version )")!==false,'provider semver shape');
$assert(strpos($tenth,'critical_health_state')!==false&&strpos($tenth,"array( 'file-20-shell', 'file-00-identity' )")!==false,'critical health keys');$assert(strpos($safe,'FutureShellV5TenthHardening::critical_health_state( $health )')!==false,'Emergency health gate');
$combined=$main.$plugin.$tenth.$slots.$safe;$assert(strpos($combined,'CREATE TABLE')===false&&strpos($combined,'dbDelta(')===false&&strpos($combined,'INSERT INTO')===false,'no foreign backend');
if($fail){fwrite(STDERR,'Future Shell v5 tenth hardening FAIL: '.implode('; ',$fail)."\n");exit(1);}echo"Future Shell v5 tenth hardening preserved under 1.4.16 PASS\n";